### ISSUE TITLE
Faciliter le passage à l’échelle

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1326]
Issue globale de différentes actions pour _anticiper la croissance_ en facilitant la gestion des sollicitations de bout en bout.

1. Évaluer l’acquisition de bout en bout pour savoir sur quels types de sollicitations concentrer nos efforts
   * [ ] C‘est la raison d’être de #1316. En cas de pic, on pourra optimiser l’acquisition sur les besoins moins saturés (voir couper carrément l’acquisition payante)
2. Afficher sur les pages thématiques un premier niveau d’information. 
   * [x] C’est déjà possible, on peut faire des paragraphes dans les pages thématiques sans lien vers une demande.
3. Faciliter la demande de précision des sollicitations de mauvaise qualité
   * [ ] Envoyer un email automatisé, un sms? avec un formulaire spécifique de saisie de détails? On a déjà un process semi-manuel avec un email prérédigé dans FrontApp.
   * :fire: En cas de pic, on voudra aussi rejeter directement les sollicitations de très mauvaise qualité, plutôt que de perdre du temps à demander des compléments d’information.
4. Visualiser la préselection des sujets à partir des options du formulaire 
   * [ ] Cf #1239 Rendre les LandingOptions plus indépendantes des Landings. Peut-être que la vue en liste dans activeadmin suffirait.
5. Sauter les étapes pour les analyses à partir des sollicitations
   * [ ] On veut pouvoir directement “envoyer les mises en relations” depuis /sollicitations.
   * Il faut que la préselection soit activée, voir le point précédent.
   * [ ] Voir aussi #610 pour le redesign des étapes de l’analyse
6. Copier-coller automatiquement le texte de la sollicitation en commentaire
   * [ ] Cf #1028: Le principal est que le texte soit affiché au bon endroit. “Copier-coller” n‘est pas un but en soit.
7. Trier les sollicitations, analyses, besoins par région, visualiser les experts par région
   * [ ] Tri par région
   * [ ] Voir aussi #1238 Unifier le design des onglets /analyses, /besoins et /sollicitations
8. Permettre de suivre le nombre de mise en relation et le taux d’échec par partenaire pour garder un oeil sur leur capacité à prendre en charge les besoins transmis
   * [ ] C’est la partie “stats partenaires” de #1088
