### ISSUE TITLE
Renommer les scopes des relances pour plus de compréhension

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1367]
Ce qui reste à faire fait l'objet d'une nouvelle issue -> #1544 

Dans le model `Need` 

---

Retravail en cours: j’en profite pour solder la dette technique accumulée dans les needs et diagnoses

Sur Need:
* [x] #1469 optimisation des queries des scopes pour éviter de devoir faire des join dans le code appelant
* [x] #1469 renommage no_help_provided en action_may_help et changement pour ne pas inclure les status_not_for_me
* [x] #1469 Factorisation des scope `reminders_to:(action)`
* [ ] Utiliser le délai d’archive pour ne pas afficher les besoins reçus et pris en compte par d’autre dans needs#index

Sur les reminders/needs et reminders/experts:
* [x] #1469 Ajout d’une route reminders_action#archive pour simplifier le code des boutons d’actions de relance
* [x] #1469 Construction dynamique du menu (comme pour needs/index)
* [x] #1469 Utiliser le même partial pour l’entête de reminders/needs et reminders/experts
* [x] #1470 Retrait des paramètres inutilisés “highlighted_experts” et “needs_of_interest”

Pour les emails et les scopes eux-mêmes:
* [x] #1472 Utiliser les scopes reminders_to pour l’email de weekly_statistics (`AdminMailerService#abandoned_needs_statistics`).
* [ ] Utiliser les scopes reminders_to pour les emails de relance hebdo (`ExpertReminderService#send_reminders`)

Sur NeedsController, DiagnosesController et Reminders/NeedsController (et ça déborde un peu sur #1278)
* [ ] Utiliser les mêmes scopes de collections pour `needs` et pour `reminders/experts/needs`, ainsi que dans l’aperçu de relance de l’expert (`reminders/experts/expert_content.haml`)
* [ ] Utiliser les même partials pour needs (`needs/_received_needs.haml` et `reminders/needs.html.haml`
* [ ] Utiliser le même partial pour diagnosis (`diagnoses/diagnosis` et `reminders/diagnosis`, `diagnoses/diagnoses`

**Comment by Adeline-Lrn** [comment]
https://docs.google.com/document/d/1vNTpNEdgmacCoAp1yw_MMaTI5PgOEFGMvGI3t-xZrQQ/edit

**Comment by clairezed** [comment]
Cf doc Outil de relance : https://docs.google.com/document/d/1vNTpNEdgmacCoAp1yw_MMaTI5PgOEFGMvGI3t-xZrQQ/edit

**Comment by clairezed** [comment]
@LucienMLD en fait, je le laisse encore tel quel cette semaine, pour essayer de l'avancer si on a le temps. En fin de semaine, on recréé une issue avec ce qu'il restera. Ca te semble ok ?
