### ISSUE TITLE
Rendre les utilisateurs autonomes sur leur rôle

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#766]
Tâche générale rassemblant plusieurs points:

* [x] Rendre les notions de suppléant et spécialiste plus clair
* [x] Faire en sorte que tous les Users puissent avoir des compétences #760
* [x] Inciter les utilisateurs à vérifier périodiquement leurs compétences #756
* [x] ~~Permettre aux utilisateurs de changer d’agence et d’équipe eux-mêmes #767~~
- [x] Arriver directement sur les compétences lors du premier login (après création du mot de passe).
- [x] Arriver directement sur les compétences lors du rappel des compétences.
* [x] Visualiser les changements dans un journal
* [x] Une fois en prod, activer le rappel de revue des champs d’intervention pour tous les utilisateurs.

De fait, c’est la suite logique de #638 :)

**Comment by n-b** [comment]
On est toujours empêtrés dans la notion d’`Expert`, qui regroupe à la fois une notion d’équipe (mais pas toujours) et de compétences (via les `ExpertSubject`). Je propose de casser ça:
* Renommer `Expert` en `Team`, qui regroupe plusieurs `User`s, avec un nom, rôle, téléphone et email d’équipe;
* Renommer `ExpertSubject` en `Skill`, et permettre de l’associer aussi bien avec une `Team` qu’avec un `User`. (Via une association polymorphique.)
* Ainsi, chaque `Team` a des `Skill`, mais chaque `User` individuellement aussi.
* Comme avant, chaque `User` peut appartenir a une ou plusieurs `Team`.
---
Sur les zones d’intervention:
* Il reste la difficulté des zones d’intervention spécifiques: différente de celle de l’antenne, ou variable selon le sujet pour un même conseiller.
* Est-ce que tous les membres d’une `Team` doivent nécessairement faire partie d’une même `Antenne`? Je ne crois pas que ce soit nécessaire au niveau du code; est-ce que c’est pertinent de le forcer? L’intérêt de l’antenne, c’est surtout de définir une zone d’intervention, mais elle peut déjà être précisée au niveau de l’équipe.
* In fine, il faut permettre aux utilisateurs de tout modifier eux-mêmes:
 * leurs compétences propres
 * leur appartenance à une antenne au sein le leur institution
 * leur appartenance à des équipes au sein de leur institution
 * la création d’équipe, voire d’antennes, au sein l’institution
 * la zone d‘intervention des équipes et des antennes.
---
* À y réfléchir, je ne suis pas sûr que les notions d’Antenne et de Team soient si séparées.

**Comment by n-b** [comment]
Notions:
========

## Notion d’**Équipe** et de **Jeu de Compétences Individuel**
* **Équipe**: Expert qui a, ou peut avoir plusieurs membres
 * autrement dit: dont au moins un membre à une adresse email différente de celle de l’équipe.
* Sinon, l’Expert correspond au **Jeu de Compétences Individuel** d’un seul utilisateur.
* Note: si un Expert a un email identique à un User, mais a plusieurs membres, il s’agit bien d’une **Équipe**, pas d’un **Jeu de Compétences Individuel** de cet User. L’User en question aura aussi un autre Expert **Jeu de Compétences Individuel**. Plusieurs Expert peuvent avoir le même email, c’est déjà le cas.

## User multi-expert
* (moins utile a priori)
* Un User peut avoir a plusieurs Experts pour plusieurs raisons:
 * Iel fait partie de plusieurs **Équipes**.
 * Iel a plusieurs **Jeux de Compétences Individuels** sur des territoires distinct.
 * Iel fait partie d’une ou plusieurs **Équipe**, et a par ailleurs un ou des **Jeux de Compétences Individuels**.

## Notion de Expert **vide**
* Expert sans aucun ExpertSubject.

Variantes d’affichages:
=======================

Onglets
-------

### Affichage des Paramètres des Experts d’un User
* Affichage d’un onglet `edit_expert_path` pour chaque **Équipe**
* pas pour les **Jeux de Compétences Individuels**
* Onglet “Paramètres d’équipe” si une seule **Équipe**
* Sous-titre “Paramètres d’équipe” si plusieurs, avec un onglet portant le nom de chaque **Équipe**.

### Affichage des Skills des Experts d’un User
* Affichage d’un onglet `skills_expert_path`
* Sont affichés:
 * tous les experts **Équipe**.
 * les **Jeux de Compétences Individuels**, dans ces deux cas:
  * l’Expert n’est pas **vide**,
  * l’User n’a pas d’**Équipe**.
* Onglet “Domaines d’intervention” si un seul Expert.
* Sous-titre “Domaines d’intervention” si plusieurs, avec un onglet portant le nom chaque Expert.

Contenu
-------

### Affichage de l’Antenne
* Sont affichés ces Experts:
 * tous les experts **Équipe**.
 * les **Jeux de Compétences Individuels**, dans ces deux cas:
  * l’Expert n’est pas **vide**,
  * l’User n’a pas d’**Équipe**.
* Liste des membres:
 * Affichage des **Équipes**, avec tous les membres.
 * Affichage des **Jeu de Compétences Individuel**, sans les membres.
 * Les détails des User sont affichés au hover.
 * Les détails des Expert sont affichés au hover.
 * Le User qui correspond à l’utilisateur courant est mis en couleur.
* Matrice des compétences:
 * Lignes: les Experts affichés.
 * Colonnes: les sujets de l’institution.

### Affichage des Paramètres d’un Expert
* Comme dit plus haut, cette vue n’existe que pour les experts **Équipe**. On affiche donc toujours la liste des membres.
* Si l’Antenne de l’**Équipe** est différente de celle de l’User, afficher un message d’alerte.
* Si l’email de l’Expert correspond à celui d’un membre, on affiche un message explicatif sur la notion d’Équipe et le renommage.

### Affichage des Skills d’un Expert
* Si l’expert est une **Équipe** qui a effectivement plusieurs membres, on affiche un message explicatif sur le partage des compétences.

Variantes de comportement:
==========================

## Modification des réglages d’un User
* Les Experts qui sont des **Jeux de Compétences Individuels** de cet Utilisateurs sont mises à jour avec les mêmes nom / email / rôle / phone / équipe que leur User.

## Création automatique d’un **Jeu de Compétences Individuel**
* Systématiquement, pour tous les Users à la création.
* En batch pour tout les Users existant qui n’ont pas de **Jeu de Compétences Individuel**.
 * Y compris s’ils font partie, par ailleurs, d’une équipe.

Raccourcis:
===========

## “Mes compétences”
* Redirige vers le premier onglet de Skills

**Comment by n-b** [comment]
c’est fait! 🍾
